Install matplotlib before building taskplot
The first Travis CI build with this error:

    $ python setup.py sdist
    Traceback (most recent call last):
      File "setup.py", line 35, in <module>
        from src import taskplot
      File "/home/travis/build/susam/taskplot/src/taskplot.py", line 162, in <module>
        from matplotlib import ticker
    ImportError: No module named 'matplotlib'

Therefore, install matplotlib before building taskplot.